# Generated by Django 5.2 on 2025-04-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_pdffile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='session_no',
            field=models.IntegerField(default=1),
        ),
    ]
