# Generated by Django 5.2 on 2025-04-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0005_add_evaluation_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentScore',
        ),
    ]
