# Generated by Django 5.2 on 2025-04-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0006_delete_studentscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrossMotorPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='gross_motor_pdfs/')),
                ('eval1_score', models.IntegerField()),
                ('eval2_score', models.IntegerField()),
                ('eval3_score', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
