# Generated by Django 5.2 on 2025-04-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0017_expressivepdfteacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='username',
            new_name='gmail',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
