# Generated by Django 5.2 on 2025-04-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0018_rename_username_student_gmail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
