# Generated by Django 5.2 on 2025-05-04 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0021_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='System.evaluationform')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('column_type', models.CharField(choices=[('text', 'Text'), ('checkbox', 'Checkbox')], default='text', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='System.evaluationrow')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
