# Generated by Django 5.2 on 2025-05-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0023_editableevaluationtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='editableevaluationtable',
            name='evaluator_type',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('PARENT', 'Parent')], default='TEACHER', max_length=10),
        ),
    ]
