# Generated by Django 5.2 on 2025-05-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0026_alter_editableevaluationtable_evaluator_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationDataTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=255)),
                ('evaluation_type', models.CharField(choices=[('GROSS_MOTOR', 'Gross Motor'), ('FINE_MOTOR', 'Fine Motor'), ('SELF_HELP', 'Self Help'), ('COGNITIVE', 'Cognitive'), ('EXPRESSIVE', 'Expressive Language'), ('RECEPTIVE', 'Receptive Language'), ('SOCIAL', 'Social-Emotional')], max_length=50)),
                ('evaluator_type', models.CharField(choices=[('TEACHER', 'Teacher'), ('PARENT', 'Parent')], max_length=10)),
                ('first_eval_score', models.IntegerField()),
                ('second_eval_score', models.IntegerField()),
                ('third_eval_score', models.IntegerField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('child_name', 'evaluation_type', 'evaluator_type')},
            },
        ),
    ]
