# Generated by Django 5.2 on 2025-05-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0027_evaluationdatateacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CognitiveEvaluation',
        ),
        migrations.DeleteModel(
            name='CognitivePDF',
        ),
        migrations.DeleteModel(
            name='CognitivePDFTeacher',
        ),
        migrations.RemoveField(
            model_name='evaluationpdf',
            name='pdf_file',
        ),
        migrations.DeleteModel(
            name='ExpressiveEvaluation',
        ),
        migrations.DeleteModel(
            name='ExpressivePDF',
        ),
        migrations.DeleteModel(
            name='ExpressivePDFTeacher',
        ),
        migrations.DeleteModel(
            name='FineEvaluation',
        ),
        migrations.DeleteModel(
            name='FinePDFTeacher',
        ),
        migrations.DeleteModel(
            name='GrossEvaluation',
        ),
        migrations.DeleteModel(
            name='GrossMotorPDF',
        ),
        migrations.DeleteModel(
            name='GrossMotorPDFTeacher',
        ),
        migrations.DeleteModel(
            name='ParentCognitiveEvaluation',
        ),
        migrations.DeleteModel(
            name='ParentExpressiveEvaluation',
        ),
        migrations.DeleteModel(
            name='ParentGrossEvaluation',
        ),
        migrations.DeleteModel(
            name='ParentSelfHelpEvaluation',
        ),
        migrations.DeleteModel(
            name='ParentSocialEvaluation',
        ),
        migrations.DeleteModel(
            name='ReceptiveEvaluation',
        ),
        migrations.DeleteModel(
            name='ReceptivePDFTeacher',
        ),
        migrations.DeleteModel(
            name='SelfHelpEvaluation',
        ),
        migrations.DeleteModel(
            name='SelfHelpPDF',
        ),
        migrations.DeleteModel(
            name='SelfHelpPDFTeacher',
        ),
        migrations.DeleteModel(
            name='SocialEvaluation',
        ),
        migrations.DeleteModel(
            name='SocialPDF',
        ),
        migrations.DeleteModel(
            name='SocialPDFTeacher',
        ),
        migrations.DeleteModel(
            name='TotalScores',
        ),
        migrations.DeleteModel(
            name='EvaluationPDF',
        ),
    ]
