# Generated by Django 5.2 on 2025-05-21 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0028_delete_cognitiveevaluation_delete_cognitivepdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='student',
            name='school_year',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
