# Generated by Django 5.2 on 2025-05-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0029_student_enrollment_date_student_school_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_year',
        ),
    ]
