# Generated by Django 5.2 on 2025-05-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0030_remove_student_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school_year',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
