# Generated by Django 5.2 on 2025-05-21 15:08

from django.db import migrations
from datetime import datetime

def update_school_year(apps, schema_editor):
    Student = apps.get_model('System', 'Student')
    current_date = datetime.now()
    
    # Update all existing students
    for student in Student.objects.all():
        student.enrollment_date = current_date
        student.school_year = "2024-2025"  # Current school year
        student.save()

def reverse_school_year(apps, schema_editor):
    Student = apps.get_model('System', 'Student')
    Student.objects.all().update(enrollment_date=None, school_year=None)

class Migration(migrations.Migration):

    dependencies = [
        ('System', '0031_student_enrollment_date_student_school_year'),
    ]

    operations = [
        migrations.RunPython(update_school_year, reverse_school_year),
    ]
