# Generated by Django 5.2 on 2025-05-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0033_schoolyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lrn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
