# Generated by Django 5.2 on 2025-04-14 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0002_alter_message_content_document_message_attachment'),
        ('System', '0002_pdffile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='System.pdffile'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
